### ISSUE TITLE
10.12.2，点击停止闪退

### ISSUE THREAD

**Issue by frank-zx** [dfdragon/kcptun_xclient#10]
启动正常，但是点击停止后就会闪退。

**Comment by reancool** [comment]
同上。

**Comment by shaunqiu** [comment]
第一次启动正常，然后配置完成之后闪退，之后每次重启都闪退

**Comment by diov** [comment]
每次启动都闪退+1

**Comment by cbyniiaii** [comment]
+1

**Comment by mtq1992** [comment]
+1

**Comment by starleafs** [comment]
不仅仅是点击停止闪退，在某些情况下，闪退之后就无法再启动了
需要删除kcptun.xml，然后再打开软件，就可以启动了，然而配置需要重新输入一遍。如果把原来删除的kcptun.xml重新导入，还是会导致无法启动。

**Comment by Alicture** [comment]
现在点击图标就闪退？

**Comment by starleafs** [comment]
是的，仔细分析了一下，发现是在某些未知情况下，kcptun.xml变成了0 bytes,然后就出现点击图标无法闪退的情况。
必须要删除这个0 bytes的kcptun.xml才行，下次打开软件会重新生成一个正确的xml文件。
但是不知道为什么kcptun.xml会变成0 bytes

**Comment by Alicture** [comment]
kcptun.xml在哪里- -没看到啊

在 2017年2月13日 下午7:31，starleafs <notifications@github.com>写道：

**Comment by Alicture** [comment]
2017-02-18 20:09:35.103 kcptun_xclient[82289:3439315] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** Call stack at first throw:
(
	0   CoreFoundation                      0x947c610b __raiseError + 187
	1   libobjc.A.dylib                     0x9ef336e6 objc_exception_throw + 273
	2   AppKit                              0x92ce019a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4080
	3   AppKit                              0x92cdf1a2 -[NSApplication(NSEvent) nextEventMatchingMask:untilDate:inMode:dequeue:] + 132
	4   kcptun_xclient                      0x00178247 TMethodImplementationIntercept + 938811
	5   kcptun_xclient                      0x004ff0b6 TMethodImplementationIntercept + 4637098
	6   kcptun_xclient                      0x004ff776 TMethodImplementationIntercept + 4638826
	7   kcptun_xclient                      0x0096de61 TMethodImplementationIntercept + 9285461
	8   kcptun_xclient                      0x000fcb49 TMethodImplementationIntercept + 433213
	9   kcptun_xclient                      0x0001943a @DbgExcNotify + 4518
	10  libsystem_pthread.dylib             0x9f99510b _pthread_body + 184
	11  libsystem_pthread.dylib             0x9f995053 _pthread_body + 0
	12  libsystem_pthread.dylib             0x9f99490e thread_start + 34
)
[1]    82289 trace trap  /Applications/kcptun_xclient.app/Contents/MacOS/kcptun_xclient
以上是详细的错误信息

**Comment by axhello** [comment]
同闪退啊 然后再也打不开了...

**Comment by Alicture** [comment]
已经放弃了直接使用终端启动
