### ISSUE TITLE
1.01闪退的解决办法

### ISSUE THREAD

**Issue by oatgnik** [dfdragon/kcptun_xclient#8]
MAC下闪退个人解决办法：
1、kcptune client的路径不能有中文
2、xclient要放到application里面

记得先清除application里面的kcptun配置文档，否则会一直闪退

我是这样解决的，可能是个例，不代表全体

**Comment by marsend** [comment]
记得先清除application里面的kcptun配置文档
请问清除方法是什么？

**Comment by marsend** [comment]
@oatgnik 
记得先清除application里面的kcptun配置文档
请问清除方法是什么？

**Comment by Radar-Lei** [comment]
感谢~

**Comment by wangliyao** [comment]
还请告知kckptun配置路径，一打开就闪退
